name: Custom ROM Builder
description: Change logo and other options
title: "[Custom coreboot Build]: "
body:
  - type: dropdown
    attributes:
      label: Firmware type
      description: Select the Full ROM option from the dropdown box.
      multiple: false
      options:
        - "Full ROM"
    validations:
      required: true
  - type: input
    id: board_name
    attributes:
      label: Board Name
      description: "Enter the board name of your Chromebook"
      placeholder: leona
    validations:
      required: true
  - type: dropdown
    attributes:
      label: DISABLE_HECI1_AT_PRE_BOOT
      description: Select "Yes" to build a ROM that fixes sleep/wake issues on macOS.
      multiple: false
      options:
        - "Yes"

